name: windows-build

on:
  push:
    branches:
      - ci/**
      - main
      - dev
      - release-0.2
  pull_request:
    branches:
      - main
      - dev
      - release-0.2
  workflow_dispatch:

jobs:
  build:
    name: Windows CPU
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build audiocpp_cli
        shell: pwsh
        run: |
          .\scripts\build_windows.ps1 `
            -Preset windows-cpu-release `
            -Target audiocpp_cli

      - name: Build audiocpp_server
        shell: pwsh
        run: |
          .\scripts\build_windows.ps1 `
            -Preset windows-cpu-release `
            -Target audiocpp_server

      - name: Build audiocpp_gguf
        shell: pwsh
        run: |
          .\scripts\build_windows.ps1 `
            -Preset windows-cpu-release `
            -Target audiocpp_gguf
